/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weanswer.v2;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class AddAnswer extends javax.swing.JFrame {
String ques;
    /**
     * Creates new form AddAnswer
     */
    public AddAnswer() {
  initComponents();
    }

    public AddAnswer(String Quesforanswer) {
            initComponents();
        ques= Quesforanswer;
        jLabel1.setText(ques);  //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        box = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        box.setColumns(20);
        box.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        box.setRows(5);
        box.setText("Type your answer...");
        jScrollPane1.setViewportView(box);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 170, 390, 90);

        jButton1.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(68, 154, 206));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 270, 130, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/WeAnswerLogo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 310, 150, 51);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/Home.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 0, 80, 70);

        jButton3.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(68, 154, 206));
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(410, 10, 101, 40);

        jLabel2.setFont(new java.awt.Font("Prime", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 154, 206));
        jLabel2.setText("Add Answer");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 20, 190, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/weanswer background.jpeg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 540, 380);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 100, 34, 14);

        setBounds(0, 0, 536, 405);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //question variable to be forwarded and to set maximumlimit on number of answers that can be provided
        String answer=box.getText();
       int i=0; int j=10;
        try{
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/weanswer","root", "Mysql19");
            Statement stmt = (Statement)con.createStatement();
            
            for(i=1; i<6; i++)
            {String query= "Select answer"+i+" from answers  where questions= '"+ques+"';";
            ResultSet rs= stmt.executeQuery(query);
            while(rs.next())
            {String l= rs.getString("answer"+i+"");
            if(l.equals("NULL"))
            {try{Class.forName("java.sql.DriverManager");
            Connection con1=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/weanswer","root", "Mysql19");
            Statement stmt1 = (Statement)con.createStatement();
            String ans= "Update answers set answer"+i+"= '"+answer+"' where questions='"+ques+"';";
            j=1;
            i=10;
            stmt1.executeUpdate(ans);}
            catch(Exception e)
            {JOptionPane.showMessageDialog(this, e.getMessage());}
            }}}
            if(j==10)
            {JOptionPane.showMessageDialog(this, "The limit of maximum number of answers has been reached!");}
            else{JOptionPane.showMessageDialog(this, "Your answer has been added. Thank you!");}}
        catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());}     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Homepage a= new Homepage();
        this.setVisible(false);
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LoginandSignup a= new LoginandSignup();
        this.setVisible(false);
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAnswer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
