/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weanswer.v2;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class AddQuestion extends javax.swing.JFrame {

    /**
     * Creates new form AddQuestion
     */
    public AddQuestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        box.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Technology", "Academics", "Sports", "Food", "Health", "Travel", "Politics", "Misc." }));
        box.setName("catagories"); // NOI18N
        box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxActionPerformed(evt);
            }
        });
        getContentPane().add(box);
        box.setBounds(310, 220, 180, 60);

        jLabel2.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 154, 206));
        jLabel2.setText("Keyword 3:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 280, 110, 40);

        jLabel3.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 154, 206));
        jLabel3.setText("Keyword 2:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 240, 110, 20);

        jLabel4.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 154, 206));
        jLabel4.setText("Keyword 1:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 110, 30);

        t1.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(140, 230, 110, 30);

        t2.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(140, 280, 110, 30);

        t3.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        getContentPane().add(t3);
        t3.setBounds(140, 190, 110, 30);

        jButton3.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(68, 154, 206));
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(370, 10, 110, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/Home.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 0, 90, 70);

        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        ta.setRows(5);
        ta.setText("What's your question?");
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 80, 335, 68);

        jLabel1.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 154, 206));
        jLabel1.setText("Categories:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 170, 110, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/WeAnswerLogo.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 340, 110, 51);

        jButton1.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(68, 154, 206));
        jButton1.setText("Ask");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 290, 90, 40);

        jLabel5.setFont(new java.awt.Font("Prime", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 154, 206));
        jLabel5.setText("Ask Us");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 10, 150, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/weanswer background.jpeg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 520, 400);

        setBounds(0, 0, 522, 424);
    }// </editor-fold>//GEN-END:initComponents

    private void boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LoginandSignup a= new LoginandSignup();
        this.setVisible(false);
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Homepage a= new Homepage();
        this.setVisible(false);
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handlin//Declare variables and store values retrieved from the

        String kw1=t2.getText();
        String kw2=t3.getText();
        String kw3=t1.getText();
        String cat=""+box.getSelectedItem();
        String ques=ta.getText();

        if(kw1.equals(" ") && " ".equals(kw2) && " ".equals(kw3) )
        {JOptionPane.showMessageDialog(null, "please enter at least one keyword");}
        if("".equals(cat))
        {JOptionPane.showMessageDialog(null,"please select a category");}
        try

        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/weanswer","root", "Mysql19");
            Statement stmt = (Statement)con.createStatement();
            Connection con1 = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/weanswer","root", "Mysql19");
            Statement stmt1 = (Statement)con1.createStatement();
            String query="INSERT INTO questions VALUES('"+ques+"','"+kw1+"','"+kw2+"','"+kw3+"','"+cat+"');";
            String query1="INSERT INTO answers VALUES('"+ques+"', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');";
            stmt.executeUpdate(query);
            stmt1.executeUpdate(query1);
            JOptionPane.showMessageDialog(null,"Your question has been added. Please wait for answer." );
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog (this, e.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
