/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weanswer.v2;
//Forward variable from question

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class DisplayAnswer extends javax.swing.JFrame {
String questoanswer;
    /**
     * Creates new form DisplayAnswer
     */
    public DisplayAnswer(){
        initComponents();
    }
    
    
public DisplayAnswer(String Quesforans) {
       initComponents();
       questoanswer= Quesforans;
       jLabel2.setText(questoanswer); 
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/Home.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 70));

        jLabel2.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 154, 206));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 430, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/WeAnswerLogo.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 110, -1));

        jButton1.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(68, 154, 206));
        jButton1.setText("Add Answer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 140, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Prime", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 460, 150));

        jButton4.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(68, 154, 206));
        jButton4.setText("View Answers");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 160, 40));

        jButton3.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(68, 154, 206));
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 110, 40));

        jLabel5.setFont(new java.awt.Font("Prime", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 154, 206));
        jLabel5.setText("View Answers");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/weanswer background.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Homepage a= new Homepage();
        this.setVisible(false);
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LoginandSignup a= new LoginandSignup();
        this.setVisible(false);
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String quesforanswer= jLabel2.getText();
        AddAnswer a= new AddAnswer(quesforanswer);
        this.setVisible(false);
        a.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       int counter=0;
       String quesforans=jLabel2.getText();
        try

        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/weanswer","root", "Mysql19");
            Statement stmt = (Statement)con.createStatement();
            String query= "Select * from answers where questions='"+quesforans+"';";
            ResultSet answers= stmt.executeQuery(query);
            while(answers.next())
            {
             String answer1=answers.getString("answer1");
             String answer2=answers.getString("answer2");
             String answer3=answers.getString("answer3");
             String answer4=answers.getString("answer4");
             String answer5=answers.getString("answer5");
             if (answer1.equals("NULL"))
             {;}
             else{jTextArea1.append(answer1 + "\n");
             counter+=1;}
             if (answer2.equals("NULL"))
             {;}
             else{jTextArea1.append(answer2 + "\n");
             counter+=1;}
             if (answer3.equals("NULL"))
             {;}
             else{jTextArea1.append(answer3 + "\n");
             counter+=1;}
             if (answer4.equals("NULL"))
             {;}
             else{jTextArea1.append(answer4 + "\n");
             counter+=1;}
             if (answer5.equals("NULL"))
             {;}
             else{jTextArea1.append(answer5 + "\n");
             counter+=1;}
             
        }
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());}        // TODO add your handling code here:
    
        if(counter==5)
    {
        jButton1.setEnabled(false);
        JOptionPane.showMessageDialog(this,"This answer has reached maximum amount of answers. Please wait for our administrators to moderate content. You may ask an alternative question if required. Apologies for the inconvevience.");
    }
        else
            jButton1.setEnabled(true);                                       
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayAnswer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
