/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weanswer.v2;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
        jLayeredPane1.setVisible(true);
        jLayeredPane2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(204, 29, 70, 0);

        jLabel6.setFont(new java.awt.Font("Prime", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(68, 154, 206));
        jLabel6.setText("Search");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 30, 160, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/WeAnswerLogo.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 270, 101, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/Home.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 10, 95, 60);

        jButton3.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(68, 154, 206));
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 20, 120, 40);

        jButton4.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(68, 154, 206));
        jButton4.setText("Add Question");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton4);
        jButton4.setBounds(460, 280, 150, 40);

        jTable1.setFont(new java.awt.Font("Prime", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(68, 154, 206));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question (Select a question)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jLayeredPane2.add(jScrollPane2);
        jScrollPane2.setBounds(60, 90, 560, 180);

        jButton5.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(68, 154, 206));
        jButton5.setText("Back to Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton5);
        jButton5.setBounds(290, 280, 163, 40);

        jButton6.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(68, 154, 206));
        jButton6.setText("View Answers ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton6);
        jButton6.setBounds(117, 280, 163, 40);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(0, 0, 640, 350);

        jLabel1.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 154, 206));
        jLabel1.setText("Question:");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(40, 100, 110, 26);

        jLabel3.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 154, 206));
        jLabel3.setText("Category:");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(50, 190, 110, 23);

        jLabel4.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 154, 206));
        jLabel4.setText("Keywords:");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(50, 230, 110, 22);

        jTextField1.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        jLayeredPane1.add(jTextField1);
        jTextField1.setBounds(150, 230, 90, 30);

        jTextField2.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jTextField2);
        jTextField2.setBounds(260, 230, 90, 30);

        jTextField3.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        jLayeredPane1.add(jTextField3);
        jTextField3.setBounds(360, 230, 90, 30);

        jComboBox1.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Technology", "Academics", "Sports", "Food", "Health", "Travel", "Politics", "Misc.", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jComboBox1);
        jComboBox1.setBounds(150, 183, 198, 30);

        jButton1.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(68, 154, 206));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(120, 290, 125, 33);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 90, 380, 50);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(10, 0, 640, 350);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/weanswer background.jpeg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 660, 350);

        setBounds(0, 0, 656, 373);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //to display data in table not use result set
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       String question= jTextArea1.getText();
        String word1= jTextField1.getText();
        String word2= jTextField2.getText();
        String word3= jTextField3.getText();
        String cat=""+jComboBox1.getSelectedItem();
        String tableques, query, query1, query2, query3;
        jLayeredPane1.setVisible(false);
        jLayeredPane2.setVisible(true);
        try

        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/weanswer","root", "Mysql19");
            Statement stmt = (Statement)con.createStatement();
            query= "Select distinct questions from questions where ((questions='"+question+"') or (keyword_1 like '%"+word1+"%' and keyword_2 like '%"+word2+"%' and keyword_3 like '%"+word3+"%') or(keyword_1 like '%"+word1+"%' or keyword_1 like '%"+word2+"%' or keyword_1 like '%"+word3+"%' or keyword_2 like '%"+word1+"%' or keyword_2 like '%"+word2+"%' or keyword_2 like '%"+word3+"%' or keyword_3 like '%"+word1+"%' or keyword_3 like '%"+word2+"%' or keyword_3 like '%"+word3+"%')) and category='"+cat+"';";
            
            ResultSet rs= stmt.executeQuery(query);
            
            while(rs.next())
            {tableques= rs.getString("questions");
            model.addRow(new Object[] {tableques});}
            
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Homepage a= new Homepage();
        this.setVisible(false);
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LoginandSignup a= new LoginandSignup();
        this.setVisible(false);
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 AddQuestion a= new AddQuestion();
        this.setVisible(false);
        a.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
jLayeredPane1.setVisible(true);
jLayeredPane2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
int column = 0;
int row = jTable1.getSelectedRow();
String quesforans = jTable1.getModel().getValueAt(row, column).toString();
this.setVisible(false);
DisplayAnswer a= new DisplayAnswer(quesforans);
        this.setVisible(false);
        a.setVisible(true); 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
