/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weanswer.v2;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Prime", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 154, 206));
        jLabel1.setText("SIGN UP HERE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 30, 190, 30);

        jLabel2.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 154, 206));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 90, 70, 20);

        jTextField1.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 80, 190, 40);

        jLabel3.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 154, 206));
        jLabel3.setText("Email ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 130, 90, 20);

        jTextField2.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 120, 190, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/WeAnswerLogo.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 10, 110, 60);

        jLabel4.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 154, 206));
        jLabel4.setText("Username:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 170, 100, 20);

        jTextField3.setFont(new java.awt.Font("Prime", 0, 18)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 160, 190, 40);

        jLabel5.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 154, 206));
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 210, 110, 20);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(210, 200, 190, 40);

        jLabel6.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(68, 154, 206));
        jLabel6.setText("Confirm Password:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 240, 180, 30);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(210, 240, 190, 40);

        jButton1.setFont(new java.awt.Font("Prime", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(79, 148, 193));
        jButton1.setText("Join Our Amazing Community!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 310, 310, 40);

        jButton2.setFont(new java.awt.Font("Prime", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(63, 152, 187));
        jButton2.setText("GO TO LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 20, 140, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weanswer/v2/weanswer background.jpeg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 600, 360);

        setBounds(0, 0, 600, 398);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name=jTextField1.getText();
        String username=jTextField3.getText();
        String password=new String(jPasswordField1.getPassword());
        String confirm=new String(jPasswordField2.getPassword());
        String emailid=jTextField2.getText();
        if(password.equals(confirm))
        {
            try{
                Class.forName("java.sql.DriverManager");
                Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/weanswer","root","Mysql19");
                Statement stmt=(Statement)con.createStatement();
                String query="INSERT INTO LOGIN VALUES('"+username+"', '"+password+"', '"+emailid+"', '"+name+"');";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(null,"You are now registered. Please login to use.");
            }
            catch(Exception e)
            { if(e.getMessage().equals("Duplicate entry '"+username+"' for key 'PRIMARY'"))
                { JOptionPane.showMessageDialog(null, "Username already taken :)");}
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Your confirmed password does not match the password you entered");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginandSignup a= new LoginandSignup();
        this.setVisible(false);
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
